# Generated by Django 4.2.6 on 2023-11-08 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('main_type', models.CharField(choices=[('f', 'Food'), ('p', 'Phone'), ('t', 'Ticket')], default='f', max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/category')),
                ('desc', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('measure', models.IntegerField(choices=[(0, 'KG'), (1, 'DONA'), (2, 'L'), (3, 'PAKET')], default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='product.category')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='product.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/subcategory')),
                ('desc', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_products', to='product.productitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('gold', 'Gold'), ('silver', 'Silver')], default='black', max_length=10)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('exc', 'Excellent'), ('used', 'Used'), ('new', 'New')], default='new', max_length=10)),
                ('model_name', models.CharField(max_length=255)),
                ('ram', models.IntegerField(choices=[(0, '4 GB'), (1, '6 GB'), (2, '8 GB'), (3, '12 GB'), (4, '16 GB'), (5, '32 GB')], default=0)),
                ('storage', models.IntegerField(choices=[(0, '32 GB'), (1, '64 GB'), (2, '128 GB'), (3, '256 GB'), (4, '512 GB'), (5, '1 TB'), (6, '2 TB')], default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='product.category')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='product.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.CharField(blank=True, max_length=255)),
                ('expire_date', models.DateField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='product.productitem')),
                ('sub_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.subcategory')),
            ],
        ),
    ]
