# Generated by Django 5.2.10 on 2026-01-14 13:36

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('main_type', models.CharField(choices=[('f', 'Oziq-ovqat'), ('p', 'Telefon'), ('t', 'Chipta')], default='f', max_length=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kr', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='category')),
                ('desc', models.TextField(blank=True)),
                ('desc_uz', models.TextField(blank=True, null=True)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('desc_ru', models.TextField(blank=True, null=True)),
                ('desc_kr', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('desc', models.TextField()),
                ('desc_uz', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
                ('desc_ru', models.TextField(null=True)),
                ('desc_kr', models.TextField(null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('product_type', models.UUIDField(default=uuid.uuid4)),
                ('new_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('weight', models.FloatField(blank=True, default=1)),
                ('measure', models.IntegerField(choices=[(0, 'KG'), (1, 'DONA'), (2, 'L'), (3, 'PAKET')], default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('main', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_type'], name='product_pro_product_6da7f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('pink', 'Pink'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('gold', 'Gold'), ('silver', 'Silver'), ('other', 'Boshqa')], default='black', max_length=10)),
                ('condition', models.CharField(choices=[('good', 'Yaxshi'), ('exc', "A'lo"), ('used', 'Foydalanilgan'), ('new', 'Yangi')], default='new', max_length=10)),
                ('model_name', models.CharField(max_length=255)),
                ('model_name_uz', models.CharField(max_length=255, null=True)),
                ('model_name_en', models.CharField(max_length=255, null=True)),
                ('model_name_ru', models.CharField(max_length=255, null=True)),
                ('model_name_kr', models.CharField(max_length=255, null=True)),
                ('ram', models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('12 GB', '12 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('other', 'Boshqa')], default=0)),
                ('storage', models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('other', 'Boshqa')], default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='product.category')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='product.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_kr', models.CharField(max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_products', to='product.productitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kr', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='subcategory')),
                ('desc', models.TextField(blank=True, null=True)),
                ('desc_uz', models.TextField(blank=True, null=True)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('desc_ru', models.TextField(blank=True, null=True)),
                ('desc_kr', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_kr', models.CharField(max_length=255, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=255)),
                ('ingredients_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients_en', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients_kr', models.CharField(blank=True, max_length=255, null=True)),
                ('expire_date', models.DateField(null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='product.productitem')),
                ('sub_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_name_uz', models.CharField(max_length=255, null=True)),
                ('event_name_en', models.CharField(max_length=255, null=True)),
                ('event_name_ru', models.CharField(max_length=255, null=True)),
                ('event_name_kr', models.CharField(max_length=255, null=True)),
                ('event_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='product.category')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='product.productitem')),
            ],
        ),
    ]
