# Generated by Django 5.2.10 on 2026-01-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('12 GB', '12 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('other', 'Boshqa')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('other', 'Boshqa')], default=0, max_length=255),
        ),
    ]
