# Generated by Django 5.2.10 on 2026-01-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_phone_ram_alter_phone_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='b2b_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text="B2B (company) mijozlar uchun narx (user.is_b2b=True bo'lsa)", max_digits=10, null=True),
        ),
    ]
