# Generated by Django 4.2.7 on 2023-11-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_image_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
