# Generated by Django 4.2.6 on 2023-10-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='category',
        ),
        migrations.AddField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='product.category'),
        ),
    ]
