# Generated by Django 4.2.7 on 2023-11-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_subcategory_active_alter_good_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='desc_kr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='desc_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='ingredients_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='ingredients_kr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='ingredients_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='ingredients_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='name_kr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name_kr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='model_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='model_name_kr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='model_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='model_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='desc_kr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='desc_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_kr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_name_kr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
