# Generated by Django 4.2.6 on 2023-10-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productitem_category_phone_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='name',
        ),
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('gold', 'Gold'), ('silver', 'Silver')], default='black', max_length=10),
        ),
    ]
