# Generated by Django 4.2.8 on 2023-12-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_desc_en_category_desc_kr_category_desc_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
