# Generated by Django 4.2.8 on 2023-12-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_soldproduct_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
