# Generated by Django 4.2.6 on 2023-10-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_phone_brand_name_remove_productitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_type',
            field=models.CharField(choices=[('f', 'Food'), ('p', 'Phone'), ('t', 'Ticket')], default='f', max_length=1),
            preserve_default=False,
        ),
    ]
