# Generated by Django 4.2.8 on 2023-12-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productitem_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
