# Generated by Django 4.2.8 on 2023-12-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productitem_price_alter_soldproduct_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='category',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='stock',
        ),
        migrations.AddField(
            model_name='productitem',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
