# Generated by Django 4.2.6 on 2023-10-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_good_sub_cat_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('exc', 'Excellent'), ('used', 'Used'), ('new', 'New')], default='new', max_length=10),
        ),
    ]
