# Generated by Django 4.2.9 on 2024-01-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_category_bonus_remove_category_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='desc_kr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='desc_uz',
            field=models.TextField(null=True),
        ),
    ]
