# Generated by Django 4.2.9 on 2024-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productitem_desc_en_productitem_desc_kr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='desc_kr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='desc_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='desc_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
