# Generated by Django 4.2.6 on 2023-11-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_type',
            field=models.CharField(choices=[('f', 'Food'), ('p', 'Phone'), ('t', 'Ticket')], default='f', max_length=1),
        ),
    ]
