# Generated by Django 4.2.9 on 2024-01-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_category_desc_alter_category_desc_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
