# Generated by Django 4.2.9 on 2024-01-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productitem_new_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
