# Generated by Django 4.2.9 on 2024-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_ticket_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='weight',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
