# Generated by Django 4.2.9 on 2024-01-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_type',
            field=models.CharField(choices=[('f', 'Oziq-ovqat'), ('p', 'Telefon'), ('t', 'Chipta')], default='f', max_length=1),
        ),
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('gold', 'Gold'), ('silver', 'Silver'), ('other', 'Boshqa')], default='black', max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='condition',
            field=models.CharField(choices=[('good', 'Yaxshi'), ('exc', "A'lo"), ('used', 'Foydalanilgan'), ('new', 'Yangi')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='weight',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
