# Generated by Django 4.2.10 on 2024-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_category_main_type_alter_phone_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.CharField(choices=[('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('12 GB', '12 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB')], default=0),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.CharField(choices=[('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB')], default=0),
        ),
    ]
