# Generated by Django 4.2.10 on 2024-02-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_phone_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='is_favorite',
        ),
    ]
