# Generated by Django 4.2.10 on 2024-03-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_phone_ram_alter_phone_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('pink', 'Pink'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('gold', 'Gold'), ('silver', 'Silver'), ('other', 'Boshqa')], default='black', max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.CharField(choices=[('2 GB', '2 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('12 GB', '12 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('other', 'Boshqa')], default=0),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB'), ('other', 'Boshqa')], default=0),
        ),
    ]
