# Generated by Django 5.0 on 2024-07-22 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_phone_color_alter_phone_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='product_type',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='productitem',
            index=models.Index(fields=['product_type'], name='product_pro_product_6da7f9_idx'),
        ),
    ]
