# Generated by Django 5.0 on 2024-07-30 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_productitem_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_type',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
