# Generated by Django 5.0 on 2024-07-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_productitem_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='main',
            field=models.BooleanField(default=True),
        ),
    ]
