from django.urls import path
from .views import (
    NewPhonesListView,
    PhoneListAPIView,
    NewTicketsListView,
    TicketListAPIView,
    SubCategoryListAPIView,
    CategoryListAPIView,
    PopularTicketsAPIView,
    PopularPhonesAPIView,
    PopularGoodAPIView,
    TicketsOnSaleListView,
    PhonesOnSaleListView,
    GoodsOnSaleListView,
    GoodListAPIView,
    NewGoodsListView,
    ImageListAPIView,
    MultiProductSearchView,
)

urlpatterns = [
    path("categories/list/", CategoryListAPIView.as_view()),
    path("subcats/list/", SubCategoryListAPIView.as_view()),
    path("tickets/list/", TicketListAPIView.as_view()),
    path("new-tickets/list/", NewTicketsListView.as_view()),
    path("popular-tickets/list/", PopularTicketsAPIView.as_view()),
    path("sale-tickets/list/", TicketsOnSaleListView.as_view()),
    path("phones/list/", PhoneListAPIView.as_view()),
    path("new-phones/list/", NewPhonesListView.as_view()),
    path("popular-phones/list/", PopularPhonesAPIView.as_view()),
    path("sale-phones/list/", PhonesOnSaleListView.as_view()),
    path("goods/list/", GoodListAPIView.as_view()),
    path("new-goods/list/", NewGoodsListView.as_view()),
    path("popular-goods/list/", PopularGoodAPIView.as_view()),
    path("sale-goods/list/", GoodsOnSaleListView.as_view()),
    path("images/list/", ImageListAPIView.as_view()),
    path("product-search/", MultiProductSearchView.as_view()),
]
