# Generated by Django 4.2.7 on 2023-11-25 09:34

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reminder', models.TextField(blank=True)),
                ('reminder_uz', models.TextField(blank=True, null=True)),
                ('reminder_en', models.TextField(blank=True, null=True)),
                ('reminder_ru', models.TextField(blank=True, null=True)),
                ('reminder_kr', models.TextField(blank=True, null=True)),
                ('agreement', models.TextField(blank=True)),
                ('agreement_uz', models.TextField(blank=True, null=True)),
                ('agreement_en', models.TextField(blank=True, null=True)),
                ('agreement_ru', models.TextField(blank=True, null=True)),
                ('agreement_kr', models.TextField(blank=True, null=True)),
                ('shipment_terms', models.TextField(blank=True)),
                ('shipment_terms_uz', models.TextField(blank=True, null=True)),
                ('shipment_terms_en', models.TextField(blank=True, null=True)),
                ('shipment_terms_ru', models.TextField(blank=True, null=True)),
                ('shipment_terms_kr', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.TextField(blank=True)),
                ('privacy_policy_uz', models.TextField(blank=True, null=True)),
                ('privacy_policy_en', models.TextField(blank=True, null=True)),
                ('privacy_policy_ru', models.TextField(blank=True, null=True)),
                ('privacy_policy_kr', models.TextField(blank=True, null=True)),
                ('about_us', models.TextField(blank=True)),
                ('about_us_uz', models.TextField(blank=True, null=True)),
                ('about_us_en', models.TextField(blank=True, null=True)),
                ('about_us_ru', models.TextField(blank=True, null=True)),
                ('about_us_kr', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
