# Generated by Django 5.2.10 on 2026-01-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_profile_referral_code'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referrer', 'referee')},
        ),
    ]
