# Generated by Django 4.2.7 on 2023-11-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='support_center',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='information',
            name='support_center_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='support_center_kr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='support_center_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='support_center_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
