# Generated by Django 4.2.8 on 2023-12-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_information_support_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_cart', 'In Cart'), ('pending', 'Pending'), ('approved', 'Approved'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='in_cart', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
