# Generated by Django 5.2.10 on 2026-01-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
