# Generated by Django 5.2.10 on 2026-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_order_bonus_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_cart', 'Savatchada'), ('pending', 'Kutilmoqda'), ('waiting_approval', 'Tasdiq kutilmoqda'), ('approved', 'Tasdiqlandi'), ('sent', 'Yuborildi'), ('cancelled', 'Bekor qilindi')], default='in_cart', max_length=20),
        ),
    ]
