# Generated by Django 4.2.8 on 2023-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='payment_data',
            field=models.TextField(blank=True),
        ),
    ]
