# Generated by Django 4.2.8 on 2023-12-15 19:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_information_payment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='payment_data_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='payment_data_kr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='payment_data_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='payment_data_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='payment_data',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
