# Generated by Django 5.2.10 on 2026-01-28 12:33

import apps.merchant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_order_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=apps.merchant.models.generate_order_number, editable=False, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_cart', 'Savatchada'), ('pending', "Admin tasdig'i kutilmoqda"), ('awaiting_payment', "To'lov qilinishi kerak"), ('check_pending', "To'lov tekshirilmoqda"), ('approved', 'Tasdiqlandi'), ('cancelled', 'Bekor qilindi')], default='in_cart', max_length=20),
        ),
    ]
