# Generated by Django 4.2.8 on 2023-12-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0009_secialmedia_alter_information_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_cart', 'Savatchada'), ('pending', 'Kutilmoqda'), ('approved', "To'lov tasdiqlandi"), ('sent', 'Yuborildi'), ('cancelled', 'Bekor qilindi')], default='in_cart', max_length=10),
        ),
    ]
