# Generated by Django 4.2.8 on 2023-12-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
