# Generated by Django 4.2.8 on 2023-12-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0011_alter_service_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=20),
        ),
    ]
