# Generated by Django 4.2.9 on 2024-01-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0014_bonus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecialMedia',
            new_name='SocialMedia',
        ),
    ]
