# Generated by Django 4.2.9 on 2024-01-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0015_rename_secialmedia_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='imo',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='kakao',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='telegram',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
