# Generated by Django 4.2.9 on 2024-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0016_alter_socialmedia_imo_alter_socialmedia_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='tiktok',
            field=models.CharField(blank=True, null=True),
        ),
    ]
