# Generated by Django 4.2.10 on 2024-02-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_profile_lang'),
        ('merchant', '0017_socialmedia_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.location'),
        ),
    ]
