# Generated by Django 5.0 on 2024-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0018_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_cart', 'Savatchada'), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('sent', 'Yuborildi'), ('cancelled', 'Bekor qilindi')], default='in_cart', max_length=10),
        ),
    ]
