# Generated by Django 4.2.6 on 2023-10-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x7f2be6a81e10>', max_length=200),
        ),
    ]
