# Generated by Django 5.2.10 on 2026-01-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default=5, upload_to='wholesaler'),
            preserve_default=False,
        ),
    ]
