# Generated by Django 4.2.7 on 2023-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
