# Generated by Django 5.2.10 on 2026-01-28 08:01

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_b2b',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='B2BApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=510)),
                ('contact_person', models.CharField(max_length=255)),
                ('extra_info', models.TextField(blank=True)),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='b2b/documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
