# Generated by Django 5.2.10 on 2026-01-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_user_is_b2b_b2bapplication'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='b2bapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='unique_pending_b2b_application_per_user'),
        ),
    ]
