# Generated by Django 4.2.8 on 2023-12-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_soldproduct_amount'),
        ('customer', '0006_news_description_en_news_description_kr_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product')},
        ),
    ]
