# Generated by Django 4.2.9 on 2024-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_news_description_alter_news_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
