# Generated by Django 4.2.10 on 2024-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_news_end_date_alter_news_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(choices=[('uz', 'UZ'), ('ru', 'RU'), ('en', 'EN'), ('kr', 'KR')], default='uz', max_length=2),
        ),
    ]
